(function(){
"use strict";
const $=id=>document.getElementById(id);const STORAGE="clash-ai-history-v2";const labels=["เปิดประเด็น","โต้แย้ง","ปิดประเด็น"];
const profiles={
 education:{words:["เรียน","นักเรียน","อาจารย์","การบ้าน","โรงเรียน","มหาวิทยาลัย","ปริญญา","สอบ"],pro:["ช่วยเปิดโอกาสให้ผู้เรียนเข้าถึงความรู้และฝึกทักษะได้ยืดหยุ่นขึ้น","หากใช้ควบคู่กับเป้าหมายการเรียนที่ชัด ผู้เรียนสามารถเห็นผลย้อนกลับและแก้จุดอ่อนได้เร็ว","ประโยชน์จะเกิดขึ้นเมื่อกำหนดขอบเขตการใช้และวัดจากความเข้าใจจริง"],con:["อาจลดการฝึกคิดด้วยตนเองและสร้างความเหลื่อมล้ำด้านการเข้าถึง","เครื่องมือไม่สามารถแทนการสอน บริบทของผู้เรียน หรือการตรวจความเข้าใจได้ทั้งหมด","จึงควรกำหนดเกณฑ์ที่ป้องกันการพึ่งพาเกินไปและรักษาความเป็นธรรม"]},
 work:{words:["งาน","ทำงาน","บริษัท","พนักงาน","เงินเดือน","อาชีพ","ธุรกิจ"],pro:["อาจเพิ่มความยืดหยุ่น ลดงานที่ไม่สร้างคุณค่า และช่วยให้คนใช้พลังกับงานสำคัญ","ถ้ากำหนดผลลัพธ์และทดลองเป็นช่วงเวลา องค์กรจะเปรียบเทียบผลก่อนตัดสินใจจริงได้","การเปลี่ยนแปลงควรมาพร้อมตัวชี้วัดเรื่องคุณภาพ ต้นทุน และความเป็นอยู่ของคนทำงาน"],con:["แต่ละอาชีพมีข้อจำกัดต่างกัน งานบริการและงานประจำจุดอาจต้องใช้คนและต้นทุนเพิ่ม","การเร่งงานให้เสร็จในเวลาน้อยลงอาจเพิ่มความกดดันและผลักภาระไปให้ผู้อื่น","ควรออกแบบให้เหมาะกับหน้างาน พร้อมเงื่อนไขยุติเมื่อคุณภาพหรือความปลอดภัยลดลง"]},
 technology:{words:["ai","เทคโนโลยี","มือถือ","อินเทอร์เน็ต","หุ่นยนต์","ออนไลน์","ข้อมูล"],pro:["ช่วยลดงานซ้ำ เปิดมุมมองใหม่ และทำให้คนเข้าถึงเครื่องมือที่เดิมมีต้นทุนสูง","เมื่อมีมนุษย์ตรวจผล เทคโนโลยีสามารถเป็นผู้ช่วยที่เพิ่มความเร็วโดยยังรักษาความรับผิดชอบ","ควรทดลองในขอบเขตเล็ก เก็บผลจริง และเปิดเผยข้อจำกัดให้ผู้ใช้เข้าใจ"],con:["อาจตอบผิด มีอคติ และทำให้ข้อมูลส่วนตัวหรือผลงานถูกใช้โดยไม่เข้าใจผลตามมา","ความสะดวกอาจทำให้คนหยุดตรวจสอบและพึ่งระบบในเรื่องที่ควรใช้วิจารณญาณ","จึงต้องมีผู้รับผิดชอบ วิธีตรวจสอบ และทางเลือกเมื่อระบบล้มเหลว"]},
 money:{words:["เงิน","ประหยัด","ภาษี","ราคา","รายได้","ค่าใช้จ่าย","เศรษฐกิจ"],pro:["อาจลดภาระค่าใช้จ่ายและทำให้ทรัพยากรถูกใช้ตรงกับความจำเป็นมากขึ้น","หากกำหนดกลุ่มเป้าหมายและติดตามผล ประโยชน์สามารถส่งถึงผู้ที่ได้รับผลกระทบจริง","ควรดูทั้งผลระยะสั้น ความคุ้มค่า และผลต่อโอกาสทางเศรษฐกิจในระยะยาว"],con:["ต้นทุนไม่ได้หายไป แต่อาจถูกย้ายไปยังงบประมาณ ผู้ประกอบการ หรือคนกลุ่มอื่น","มาตรการเดียวกันอาจให้ผลไม่เท่ากันและสร้างพฤติกรรมที่ไม่ได้ตั้งใจ","การตัดสินใจควรเปิดเผยแหล่งเงิน เกณฑ์ช่วยเหลือ และผลกระทบต่อทุกฝ่าย"]},
 food:{words:["อาหาร","กิน","อร่อย","ข้าว","กะเพรา","กระเพรา","ขาหมู","ก๋วยเตี๋ยว","หมู","ไก่","เมนู"],pro:["มีจุดเด่นด้านกลิ่น รส และความสดใหม่ ซึ่งเลือกปรับให้เข้ากับความชอบได้","ความอร่อยขึ้นอยู่กับวัตถุดิบ ฝีมือร้าน และรสที่แต่ละคนชอบ จึงควรดูประสบการณ์จริงมากกว่าชื่อเมนู","ถ้าต้องเลือก ควรดูทั้งรสชาติ ราคา ปริมาณ และความเหมาะกับมื้อนั้น"],con:["อีกตัวเลือกอาจให้รสสัมผัสและความกลมกล่อมที่ตอบโจทย์คนละแบบ","คำว่าอร่อยไม่มีคะแนนตายตัว เมนูที่เข้มข้นกว่าอาจไม่เหมาะกับคนที่ชอบรสเบาหรือคุมอาหาร","ผลตัดสินจึงเป็นคำแนะนำตามเหตุผล ไม่ใช่คำตอบแทนรสนิยมของทุกคน"]},
 society:{words:["สังคม","กฎหมาย","รัฐบาล","ห้าม","ควร","สิทธิ","ประชาชน"],pro:["อาจสร้างมาตรฐานร่วมและลดผลกระทบที่บุคคลหนึ่งสร้างต่อผู้อื่น","หากกติกาชัด โปร่งใส และใช้เท่าเทียม จะช่วยให้คนคาดการณ์ผลของการตัดสินใจได้","ควรเริ่มจากหลักฐาน รับฟังผู้ได้รับผลกระทบ และทบทวนกติกาเมื่อบริบทเปลี่ยน"],con:["กติกาที่กว้างเกินไปอาจจำกัดเสรีภาพและกระทบคนที่มีบริบทแตกต่างกัน","การบังคับใช้มีต้นทุนและอาจไม่เป็นธรรม หากเกณฑ์คลุมเครือหรือไม่มีช่องทางอุทธรณ์","ทางเลือกที่เบากว่า เช่น ให้ข้อมูลหรือทดลองสมัครใจ ควรถูกพิจารณาก่อน"]},
 general:{words:[],pro:["มีโอกาสสร้างประโยชน์เมื่อกำหนดเป้าหมาย ผู้รับผิดชอบ และขอบเขตให้ชัดเจน","การทดลองแบบวัดผลได้ช่วยแยกความเชื่อออกจากผลที่เกิดขึ้นจริง","ข้อเสนอนี้จึงควรเริ่มจากขนาดเล็กและปรับตามหลักฐาน"],con:["ประโยชน์ที่คาดหวังอาจไม่เกิดกับทุกคน และอาจมีต้นทุนที่ถูกมองข้าม","ก่อนตัดสินใจควรถามว่าใครได้รับผล ใครรับความเสี่ยง และมีทางย้อนกลับหรือไม่","ควรเปรียบเทียบทางเลือกอื่นด้วยเกณฑ์เดียวกัน ไม่ตัดสินจากความน่าสนใจของแนวคิดเพียงอย่างเดียว"]}
};
let match=null,step=0,autoTimer=null,toastTimer=null;
function profileFor(topic){const lower=topic.toLowerCase();const ranked=Object.entries(profiles).filter(([key])=>key!=="general").map(([,profile])=>({profile,score:profile.words.filter(word=>lower.includes(word)).length})).sort((a,b)=>b.score-a.score);return ranked[0]?.score?ranked[0].profile:profiles.general;}
function hash(text){let value=2166136261;for(const char of text){value^=char.charCodeAt(0);value=Math.imul(value,16777619);}return value>>>0;}
function comparisonOptions(topic){if(!/(?:อะไร|อันไหน|เมนูไหน|แบบไหน|ดีกว่า|อร่อยกว่า|เหมาะกว่า|คุ้มกว่า|เลือก)/u.test(topic))return null;const parts=topic.split(/\s*(?:กับ|หรือ)\s*/);if(parts.length!==2)return null;const left=parts[0].replace(/^ระหว่าง\s*/,"").trim();const right=parts[1].replace(/\s*(?:อะไร|อันไหน|เมนูไหน|แบบไหน).*$/u,"").replace(/[?？]/g,"").trim();return left.length>1&&right.length>1?{left,right}:null;}
function createComparisonDebate(topic,options,h){const {left,right}=options;const pro=[7+h%3,7+(h>>>3)%3,7+(h>>>6)%3],con=[7+(h>>>9)%3,7+(h>>>12)%3,7+(h>>>15)%3];const food=profiles.food.words.some(word=>topic.toLowerCase().includes(word));const rounds=food?[{pro:`ฝ่ายเห็นด้วยเลือก “${left}” เพราะเสน่ห์อยู่ที่กลิ่นเครื่องปรุง รสที่ชัด และสั่งปรับระดับความเผ็ดหรือเครื่องเคียงได้ จึงเหมาะกับคนที่อยากได้มื้อรวดเร็วแต่รสจัดจ้าน`,con:`ฝ่ายไม่เห็นด้วยเลือก “${right}” เพราะเด่นที่เนื้อสัมผัสนุ่ม น้ำราดกลมกล่อม และมีเครื่องเคียงช่วยตัดรส จึงเหมาะกับคนที่ชอบอาหารรสนุ่มลึกและอิ่มนาน`},{pro:`ข้อได้เปรียบของ “${left}” คือความหอมและรสสดจากการปรุงจานต่อจาน แต่คุณภาพอาจต่างกันตามฝีมือร้านและอาจมันหรือเค็มเกินไปได้`,con:`“${right}” ให้ความเข้มข้นและสัมผัสที่เป็นเอกลักษณ์ แต่บางคนอาจรู้สึกเลี่ยนหรือกังวลเรื่องไขมัน จึงไม่ได้ชนะสำหรับทุกคน`},{pro:`ถ้าชอบรสจัด กลิ่นหอม และเลือกเนื้อหรือไข่ดาวได้ง่าย “${left}” มีเหตุผลให้เลือกมากกว่า`,con:`ถ้าชอบเนื้อนุ่ม รสหวานเค็มกลมกล่อม และมื้อที่อยู่ท้อง “${right}” น่าเลือกกว่า สุดท้ายความอร่อยขึ้นกับร้านและรสนิยมส่วนตัว`}]:[{pro:`ฝ่ายเห็นด้วยเลือก “${left}” เพราะมีจุดแข็งที่ตอบโจทย์หัวข้อโดยตรง และเหมาะกับคนที่ให้ความสำคัญกับความยืดหยุ่นและการใช้งานจริง`,con:`ฝ่ายไม่เห็นด้วยเลือก “${right}” เพราะให้ข้อดีอีกแบบหนึ่ง และอาจเหมาะกว่าเมื่อบริบทหรือความต้องการของผู้ใช้ต่างออกไป`},{pro:`จุดแข็งของ “${left}” จะชัดเมื่อดูจากผลลัพธ์ที่ต้องการ แต่ควรยอมรับข้อจำกัดและไม่สรุปว่าเหมาะกับทุกคน`,con:`“${right}” อาจดูด้อยกว่าในเกณฑ์แรก แต่สามารถชนะได้หากให้ค่าน้ำหนักกับต้นทุน ความง่าย หรือความเหมาะเฉพาะสถานการณ์`},{pro:`ฝ่ายเห็นด้วยยังเลือก “${left}” เมื่อใช้เกณฑ์หลักของคำถามเป็นตัวตัดสิน`,con:`ฝ่ายไม่เห็นด้วยสรุปว่า “${right}” เป็นคำตอบที่สมเหตุผลสำหรับคนที่มีลำดับความสำคัญต่างกัน จึงควรเลือกตามบริบทจริง`}];return{topic,date:new Date().toISOString(),step:0,vote:"",rounds,scores:{pro,con},verdict:""};}
function createDebate(topic){const h=hash(topic),comparison=comparisonOptions(topic);if(comparison)return createComparisonDebate(topic,comparison,h);const p=profileFor(topic),pro=[7+h%3,7+(h>>>3)%3,7+(h>>>6)%3],con=[7+(h>>>9)%3,7+(h>>>12)%3,7+(h>>>15)%3];return{topic,date:new Date().toISOString(),step:0,vote:"",rounds:[{pro:`ฝ่ายเห็นด้วยมองว่า “${topic}” ${p.pro[0]} อย่างไรก็ตาม ควรกำหนดเงื่อนไขให้ชัดและประเมินผลที่เกิดขึ้นจริง`,con:`ฝ่ายไม่เห็นด้วยเตือนว่า “${topic}” ${p.con[0]} จึงควรพิจารณาข้อเสียควบคู่กับประโยชน์ที่คาดหวัง`},{pro:`ข้อกังวลของอีกฝ่ายมีน้ำหนัก แต่ไม่ได้แปลว่าต้องปฏิเสธทั้งหมด ${p.pro[1]}`,con:`แม้ฝ่ายเสนอจะชี้ประโยชน์ได้ แต่ ${p.con[1]} จึงต้องมีวิธีตรวจสอบผลและรับมือเมื่อไม่เป็นไปตามคาด`},{pro:`ฝ่ายเห็นด้วยสรุปว่า ${p.pro[2]} โดยควรพร้อมปรับตามข้อมูลใหม่`,con:`ฝ่ายไม่เห็นด้วยสรุปว่า ${p.con[2]} ก่อนตัดสินใจควรเปรียบเทียบผลกระทบของทั้งสองทางเลือก`}],scores:{pro,con},verdict:""};}
function total(side){return match.scores[side].reduce((a,b)=>a+b,0)}
function winner(){const a=total("pro"),b=total("con");return a===b?"เสมอ":a>b?"ฝ่ายเห็นด้วย":"ฝ่ายไม่เห็นด้วย"}
function verdict(){const result=winner();return result==="เสมอ"?"ทั้งสองฝ่ายให้เหตุผลใกล้เคียงกัน ฝ่ายเห็นด้วยเสนอการทดลองอย่างมีเงื่อนไข ส่วนฝ่ายไม่เห็นด้วยชี้ผู้รับความเสี่ยงและข้อจำกัดได้ชัด ควรหาข้อมูลจริงของประเด็นนี้เพิ่มก่อนตัดสินใจ":"กรรมการจำลองให้ "+result+" โน้มน้าวได้ดีกว่าเล็กน้อยจากความชัดเจน ความตรงประเด็น และการตอบข้อโต้แย้ง อย่างไรก็ตาม อีกฝ่ายยังชี้ความเสี่ยงที่ควรนำไปตรวจสอบก่อนตัดสินใจจริง";}
function save(){if(!match)return;match.step=step;const list=history().filter(x=>x.date!==match.date);list.unshift(match);try{localStorage.setItem(STORAGE,JSON.stringify(list.slice(0,8)));}catch{}renderHistory();}
function history(){try{const value=JSON.parse(localStorage.getItem(STORAGE)||"[]");return Array.isArray(value)?value.filter(valid).slice(0,8):[]}catch{return[]}}
function valid(x){return x&&typeof x.topic==="string"&&x.topic.length<=180&&Array.isArray(x.rounds)&&x.rounds.length===3&&x.scores&&Array.isArray(x.scores.pro)&&Array.isArray(x.scores.con)}
function showArgument(side,text,visible,label){const el=$(side+"-argument");el.classList.toggle("empty",!visible);el.innerHTML=visible?`<span class="round-label">${label}</span><p></p>`:`<span class="empty-symbol">${side==="pro"?"+":"−"}</span><strong>รอเปิดอีกมุมคิด</strong><p>ใช้ปุ่มด้านล่างเพื่ออ่านต่อ</p>`;if(visible)el.querySelector("p").textContent=text;}
function render(){if(!match)return;const round=Math.min(2,Math.floor(step/2)),finished=step===6,side=step%2===0?"pro":"con";$("debate-topic").textContent=match.topic;$("round-badge").textContent=finished?"FINAL VERDICT":`ROUND 0${round+1} / 03`;$("progress-bar").style.width=(finished?100:((step+1)/7)*100)+"%";document.querySelectorAll(".steps li").forEach((el,i)=>{el.classList.toggle("reached",i<=round);el.classList.toggle("current",i===round&&!finished)});if(finished){showArgument("pro",match.rounds[2].pro,true,labels[2]);showArgument("con",match.rounds[2].con,true,labels[2]);$("live-status").innerHTML="<span>จบการประลอง</span><strong>เปิดผลตัดสินแล้ว</strong>";}else{showArgument("pro",match.rounds[round].pro,true,labels[round]);showArgument("con",match.rounds[round].con,step%2===1,labels[round]);$("live-status").innerHTML=`<span>รอบ ${round+1} · ${labels[round]}</span><strong>${side==="pro"?"ฝ่ายเห็นด้วย":"ฝ่ายไม่เห็นด้วย"} กำลังนำเสนอ</strong>`;}["pro","con"].forEach(s=>{$(s+"-card").classList.toggle("active",!finished&&s===side);$(s+"-state").textContent=finished?"✓ จบการอภิปราย":s===side?"กำลังนำเสนอ":step%2===1&&s==="pro"?"นำเสนอแล้ว":"รอเปิดเหตุผล";$(s+"-state").classList.toggle("speaking",!finished&&s===side)});$("back-button").disabled=step===0;$("auto-button").disabled=finished;$("next-button").disabled=finished;$("next-button").textContent=step===5?"เปิดผลตัดสิน →":step%2===0?"อ่านฝ่ายไม่เห็นด้วย →":`ขึ้นรอบ ${round+2} →`;$("verdict").hidden=!finished;if(finished){stopAuto();renderVerdict();requestAnimationFrame(()=>$("verdict").scrollIntoView({behavior:reduce()?"auto":"smooth",block:"start"}));}save();}
function renderVerdict(){const result=winner();$("winner-title").textContent=result==="เสมอ"?"สูสี จนต้องฟังทั้งสองฝั่ง.":result+" โน้มน้าวได้ดีกว่า";$("verdict-text").textContent=verdict();["pro","con"].forEach(side=>{$(side+"-total").textContent=total(side);$(side+"-scores").innerHTML=["ความชัดเจน","ตรงประเด็น","ตอบข้อโต้แย้ง"].map((label,i)=>`<div class="score-row"><div class="score-label"><span>${label}</span><b>${match.scores[side][i]}/10</b></div><div class="score-bar"><span style="width:${match.scores[side][i]*10}%"></span></div></div>`).join("")});document.querySelectorAll("[data-vote]").forEach(b=>b.classList.toggle("selected",b.dataset.vote===match.vote));$("vote-message").textContent=match.vote?`คุณเลือก ${match.vote}${match.vote===result?" · ตรงกับกรรมการจำลอง":" · ต่างจากกรรมการจำลอง และนั่นคืออีกมุมคิด"}`:"เลือกจากเหตุผลที่ได้อ่าน เปลี่ยนใจได้เสมอ";}
function move(delta){step=Math.max(0,Math.min(6,step+delta));render();}
function stopAuto(){clearTimeout(autoTimer);autoTimer=null;$("auto-button").textContent="▶ เล่นอัตโนมัติ";$("auto-button").classList.remove("active")}
function schedule(){if(autoTimer===null||step===6)return;autoTimer=setTimeout(()=>{move(1);if(step<6)schedule()},9000)}
function toggleAuto(){if(autoTimer!==null){stopAuto();return}autoTimer=0;$("auto-button").textContent="Ⅱ หยุดอัตโนมัติ";$("auto-button").classList.add("active");schedule()}
function toast(message){clearTimeout(toastTimer);$("toast").textContent=message;$("toast").classList.add("show");toastTimer=setTimeout(()=>$("toast").classList.remove("show"),2200)}
function openPage(page){stopAuto();$("arena-page").hidden=page!=="arena";$("history-page").hidden=page!=="history";document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.page===page));if(page==="history")renderHistory();}
function renderHistory(){const list=history();$("history-count").textContent=list.length;$("empty-history").hidden=list.length>0;const root=$("history-list");root.className="history-list";root.innerHTML="";list.forEach((item,index)=>{const b=document.createElement("button");b.className="history-item";const date=new Date(item.date);b.innerHTML=`<span><small>${Number.isNaN(date.getTime())?"ไม่ระบุวันที่":date.toLocaleDateString("th-TH")} · ${item.step===6?"จบแล้ว":`ค้างที่รอบ ${Math.floor(item.step/2)+1}`}</small><strong></strong></span><b>${item.step===6?"ดูผล":"อ่านต่อ"} ↗</b>`;b.querySelector("strong").textContent=item.topic;b.addEventListener("click",()=>{match=item;step=Math.max(0,Math.min(6,Number(item.step)||0));openPage("arena");render();$("arena").scrollIntoView({behavior:reduce()?"auto":"smooth"})});root.appendChild(b)});}
function reduce(){return matchMedia("(prefers-reduced-motion: reduce)").matches}
$("topic-form").addEventListener("submit",e=>{e.preventDefault();const topic=$("topic").value.trim();if(topic.length<5){$("form-error").textContent="กรุณาพิมพ์ประเด็นอย่างน้อย 5 ตัวอักษร";$("form-error").hidden=false;return}$("form-error").hidden=true;match=createDebate(topic);step=0;render();$("arena").scrollIntoView({behavior:reduce()?"auto":"smooth",block:"start"});$("arena").focus({preventScroll:true})});
$("topic").addEventListener("input",()=>{$("char-count").textContent=$("topic").value.length+"/180";$("form-error").hidden=true});document.querySelectorAll("[data-topic]").forEach(b=>b.addEventListener("click",()=>{$("topic").value=b.dataset.topic;$("topic").dispatchEvent(new Event("input"));$("topic").focus()}));document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>openPage(b.dataset.page)));document.querySelectorAll("[data-open-arena]").forEach(b=>b.addEventListener("click",()=>openPage("arena")));
$("next-button").addEventListener("click",()=>move(1));$("back-button").addEventListener("click",()=>{stopAuto();move(-1)});$("auto-button").addEventListener("click",toggleAuto);$("restart-button").addEventListener("click",()=>{stopAuto();match=null;step=0;$("verdict").hidden=true;$("debate-topic").textContent="สนามพร้อมแล้ว — ใส่ประเด็นเพื่อเริ่ม";$("round-badge").textContent="STANDBY";$("live-status").innerHTML="<span>พร้อมรับประเด็น</span><strong>ระบบจะนำเสนอทีละฝ่าย</strong>";$("progress-bar").style.width="0";showArgument("pro","",false,"");showArgument("con","",false,"");document.querySelectorAll(".fighter").forEach(card=>card.classList.remove("active"));document.querySelectorAll(".steps li").forEach(item=>item.classList.remove("reached","current"));$("pro-state").textContent="พร้อมเข้าประลอง";$("con-state").textContent="พร้อมเข้าประลอง";$("back-button").disabled=true;$("auto-button").disabled=true;$("next-button").disabled=true;$("next-button").textContent="เริ่มจากช่องด้านบน ↑";window.scrollTo({top:0,behavior:reduce()?"auto":"smooth"});$("topic").focus()});
document.querySelectorAll("[data-vote]").forEach(b=>b.addEventListener("click",()=>{if(!match)return;match.vote=b.dataset.vote;renderVerdict();save()}));$("copy-button").addEventListener("click",async()=>{if(!match)return;const text=`CLASH AI\nประเด็น: ${match.topic}\nผลกรรมการจำลอง: ${winner()}\nคะแนน เห็นด้วย ${total("pro")}/30 · ไม่เห็นด้วย ${total("con")}/30\n${verdict()}`;try{await navigator.clipboard.writeText(text);toast("คัดลอกสรุปแล้ว")}catch{toast("เบราว์เซอร์ไม่อนุญาตให้คัดลอก")}});document.addEventListener("visibilitychange",()=>{if(document.hidden)stopAuto()});
$("char-count").textContent=$("topic").value.length+"/180";renderHistory();
})();
